### PR TITLE
My implementation for compact view

### PR DESCRIPTION
**Pull request by nishimaki10**
For [#2913](https://github.com/RocketChat/Rocket.Chat/pull/2913)

- Right side info and username ([see also](https://github.com/RocketChat/Rocket.Chat/issues/2906#issuecomment-210639335))
- I want to show role tag
- Add username to title attr for Avatar (It is displayed on mouse-over)

What do you think?

Screenshot:
my

### CODE REVIEW

**Comment by lvh1** [comment]
Hmm I don't know, I asked my users and they aren't really a fan of it.
Also, how does it look like on mobile, isn't it too crowded?
Anyway what you also could do is add a fourth option to the dropdown, that way everyone is happy :)

**Comment by nishimaki10** [comment]
> add a fourth option to the dropdown

I think that it is one of the idea, but I thought that there is endless... :anguished: 

Another idea, e.g. You put the name "IRC-Like" rather than "Compact". And, my implementation is to add a different name.
In other words, it is the "Theme".

**Comment by lvh1** [comment]
You mean this https://github.com/RocketChat/Rocket.Chat/issues/2881? :D 
That would be maximum customizability, but I wouldn't really know how to implement that properly

**Comment by nishimaki10** [comment]
Nope, I also do not know that much of it. Sorry, I meen the "View mode". I was overlooked.

OK. I close this. My implementation will PR as a different thing.
Thanks!

**Pull request closed without merging**
